In [17]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)


[1 2 3 4 5]


In [ ]:
arr2 = np.array([
                 [1,2,3,4,5],
                 [6,7,8,9,10]
])

print(arr2)

In [ ]:
# 문자열 slicing

print(arr2[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
# 파일을 가져오는 형태 잡기

from google.colab import files
uploaded = files.upload()

In [ ]:
# 파일 불러오기

import numpy as np
quest = np.loadtxt("quest.csv",delimiter = ",",dtype = np.int64)
print(quest)

[[1 2 1 2 2]
 [1 3 2 3 2]
 [1 4 3 3 3]
 [2 5 4 4 4]
 [2 5 6 2 5]
 [3 6 4 2 5]
 [3 5 4 1 6]
 [3 5 5 1 3]]


In [ ]:
quest.mean()

3.2

In [ ]:
quest.sum(axis=1)

array([ 8, 11, 14, 19, 20, 20, 19, 17])

In [ ]:
quest.cumsum()

array([  1,   3,   4,   6,   8,   9,  12,  14,  17,  19,  20,  24,  27,
        30,  33,  35,  40,  44,  48,  52,  54,  59,  65,  67,  72,  75,
        81,  85,  87,  92,  95, 100, 104, 105, 111, 114, 119, 124, 125,
       128])

In [ ]:
# 6 이상의 값을 5로 변경

quest[quest>5] = 5
print(quest)

[[1 2 1 2 2]
 [1 3 2 3 2]
 [1 4 3 3 3]
 [2 5 4 4 4]
 [2 5 5 2 5]
 [3 5 4 2 5]
 [3 5 4 1 5]
 [3 5 5 1 3]]


In [6]:
discount = .05
cashflow = 100

def presentValue(n):
  return (cashflow / ((1+discount)**n))

In [7]:
print(presentValue(1))

95.23809523809524


In [11]:
for i in range(21):
  print(presentValue(i))

100.0
95.23809523809524
90.70294784580499
86.3837598531476
82.27024747918819
78.35261664684589
74.62153966366274
71.06813301301213
67.6839362028687
64.46089162177971
61.39132535407592
58.46792890864373
55.68374181775592
53.03213506452945
50.506795299551854
48.101709809096995
45.811152199140004
43.62966876108571
41.5520654867483
39.57339570166504
37.68894828730004


In [19]:
loss = [-750,-250]
pro = [100] * 18

cf = loss + pro

np_cf = np.array(cf)
print(np_cf)

[-750 -250  100  100  100  100  100  100  100  100  100  100  100  100
  100  100  100  100  100  100]


In [22]:
!pip install numpy_financial

import numpy_financial as npf

0.5672303344358536


In [23]:
print(npf.irr([-250000, 100000, 150000, 200000, 250000, 300000]))

0.5672303344358536
