In [ ]:
import numpy as np;


[[ 1  2  3  4  5]
 [ 2  4  5  6  7]
 [ 5  7  8  9 10]]


In [ ]:
d = np.array([
              [1,2,3,4,5],
              [2,4,5,6,7],
              [5,7,8,9,10]
              ])
print(d)

[[ 1  2  3  4  5]
 [ 2  4  5  6  7]
 [ 5  7  8  9 10]]


In [ ]:
print(d[0:2,2:])

[[3 4 5]
 [5 6 7]]


* 배열의 크기 알아내기 : shape

In [ ]:
d.shape

AttributeError: ignored

In [ ]:
e = np.array([2,3,4,5,6])
e.shape

(5,)

In [ ]:
data = np.arange(1,5)
data.dtype

dtype('int64')

In [ ]:
data.astype("float64")

array([1., 2., 3., 4.])

In [ ]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
nameList = ["윤현준","jun","hyunjun","yun"]
ageList=  [17,18,19,20]

nameList + ageList

['윤현준', 'jun', 'hyunjun', 'yun', 17, 18, 19, 20]

In [ ]:
d = np.array([
              [1,2,3,4,5],
              [2,4,5,6,7],
              [5,7,8,9,10]
              ])
d_list = d
print(d)
print(d_list)

[[ 1  2  3  4  5]
 [ 2  4  5  6  7]
 [ 5  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 2  4  5  6  7]
 [ 5  7  8  9 10]]


In [ ]:
d[:2] = 0
print(d)

[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 5  7  8  9 10]]


In [45]:
print(nameList)

print(nameList[:3])

['윤현준', 'jun', 'hyunjun', 'yun']
['윤현준', 'jun', 'hyunjun']
